# JPA
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update 

  # MySql
  datasource:
    url: jdbc:mysql://localhost/epcafes
    username: root
    password: ifsp
    
  # Connection Pool
  hikari:    
    connection-timeout: 20000
    minimum-idle: 10
    maximum-pool-size: 10
    idle-timeout: 10000
    max-lifetime: 1000
    auto-commit: true